/* SPDX-License-Identifier: (GPL-2.0+ OR MIT) */
/*
 * Copyright (c) 2019 Amlogic, Inc. All rights reserved.
 */

#ifndef DOS_REGS_FB_HEADER_
#define DOS_REGS_FB_HEADER_

/* from s5 */
#define HEVC_MSP_DBE                      (0x3800 | MASK_S5_NEW_REGS)
#define HEVC_MPSR_DBE                     (0x3801 | MASK_S5_NEW_REGS)
#define HEVC_MINT_VEC_BASE_DBE            (0x3802 | MASK_S5_NEW_REGS)
#define HEVC_MCPU_INTR_GRP_DBE            (0x3803 | MASK_S5_NEW_REGS)
#define HEVC_MCPU_INTR_MSK_DBE            (0x3804 | MASK_S5_NEW_REGS)
#define HEVC_MCPU_INTR_REQ_DBE            (0x3805 | MASK_S5_NEW_REGS)
#define HEVC_MPC_P_DBE                    (0x3806 | MASK_S5_NEW_REGS)
#define HEVC_MPC_D_DBE                    (0x3807 | MASK_S5_NEW_REGS)
#define HEVC_MPC_E_DBE                    (0x3808 | MASK_S5_NEW_REGS)
#define HEVC_MPC_W_DBE                    (0x3809 | MASK_S5_NEW_REGS)
#define HEVC_MINDEX0_REG_DBE              (0x380a | MASK_S5_NEW_REGS)
#define HEVC_MINDEX1_REG_DBE              (0x380b | MASK_S5_NEW_REGS)
#define HEVC_MINDEX2_REG_DBE              (0x380c | MASK_S5_NEW_REGS)
#define HEVC_MINDEX3_REG_DBE              (0x380d | MASK_S5_NEW_REGS)
#define HEVC_MINDEX4_REG_DBE              (0x380e | MASK_S5_NEW_REGS)
#define HEVC_MINDEX5_REG_DBE              (0x380f | MASK_S5_NEW_REGS)
#define HEVC_MINDEX6_REG_DBE              (0x3810 | MASK_S5_NEW_REGS)
#define HEVC_MINDEX7_REG_DBE              (0x3811 | MASK_S5_NEW_REGS)
#define HEVC_MMIN_REG_DBE                 (0x3812 | MASK_S5_NEW_REGS)
#define HEVC_MMAX_REG_DBE                 (0x3813 | MASK_S5_NEW_REGS)
#define HEVC_MBREAK0_REG_DBE              (0x3814 | MASK_S5_NEW_REGS)
#define HEVC_MBREAK1_REG_DBE              (0x3815 | MASK_S5_NEW_REGS)
#define HEVC_MBREAK2_REG_DBE              (0x3816 | MASK_S5_NEW_REGS)
#define HEVC_MBREAK3_REG_DBE              (0x3817 | MASK_S5_NEW_REGS)
#define HEVC_MBREAK_TYPE_DBE              (0x3818 | MASK_S5_NEW_REGS)
#define HEVC_MBREAK_CTRL_DBE              (0x3819 | MASK_S5_NEW_REGS)
#define HEVC_MBREAK_STAUTS_DBE            (0x381a | MASK_S5_NEW_REGS)
#define HEVC_MDB_ADDR_REG_DBE             (0x381b | MASK_S5_NEW_REGS)
#define HEVC_MDB_DATA_REG_DBE             (0x381c | MASK_S5_NEW_REGS)
#define HEVC_MDB_CTRL_DBE                 (0x381d | MASK_S5_NEW_REGS)
#define HEVC_MSFTINT0_DBE                 (0x381e | MASK_S5_NEW_REGS)
#define HEVC_MSFTINT1_DBE                 (0x381f | MASK_S5_NEW_REGS)
#define HEVC_CSP_DBE                      (0x3820 | MASK_S5_NEW_REGS)
#define HEVC_CPSR_DBE                     (0x3821 | MASK_S5_NEW_REGS)
#define HEVC_CINT_VEC_BASE_DBE            (0x3822 | MASK_S5_NEW_REGS)
#define HEVC_CCPU_INTR_GRP_DBE            (0x3823 | MASK_S5_NEW_REGS)
#define HEVC_CCPU_INTR_MSK_DBE            (0x3824 | MASK_S5_NEW_REGS)
#define HEVC_CCPU_INTR_REQ_DBE            (0x3825 | MASK_S5_NEW_REGS)
#define HEVC_CPC_P_DBE                    (0x3826 | MASK_S5_NEW_REGS)
#define HEVC_CPC_D_DBE                    (0x3827 | MASK_S5_NEW_REGS)
#define HEVC_CPC_E_DBE                    (0x3828 | MASK_S5_NEW_REGS)
#define HEVC_CPC_W_DBE                    (0x3829 | MASK_S5_NEW_REGS)
#define HEVC_CINDEX0_REG_DBE              (0x382a | MASK_S5_NEW_REGS)
#define HEVC_CINDEX1_REG_DBE              (0x382b | MASK_S5_NEW_REGS)
#define HEVC_CINDEX2_REG_DBE              (0x382c | MASK_S5_NEW_REGS)
#define HEVC_CINDEX3_REG_DBE              (0x382d | MASK_S5_NEW_REGS)
#define HEVC_CINDEX4_REG_DBE              (0x382e | MASK_S5_NEW_REGS)
#define HEVC_CINDEX5_REG_DBE              (0x382f | MASK_S5_NEW_REGS)
#define HEVC_CINDEX6_REG_DBE              (0x3830 | MASK_S5_NEW_REGS)
#define HEVC_CINDEX7_REG_DBE              (0x3831 | MASK_S5_NEW_REGS)
#define HEVC_CMIN_REG_DBE                 (0x3832 | MASK_S5_NEW_REGS)
#define HEVC_CMAX_REG_DBE                 (0x3833 | MASK_S5_NEW_REGS)
#define HEVC_CBREAK0_REG_DBE              (0x3834 | MASK_S5_NEW_REGS)
#define HEVC_CBREAK1_REG_DBE              (0x3835 | MASK_S5_NEW_REGS)
#define HEVC_CBREAK2_REG_DBE              (0x3836 | MASK_S5_NEW_REGS)
#define HEVC_CBREAK3_REG_DBE              (0x3837 | MASK_S5_NEW_REGS)
#define HEVC_CBREAK_TYPE_DBE              (0x3838 | MASK_S5_NEW_REGS)
#define HEVC_CBREAK_CTRL_DBE              (0x3839 | MASK_S5_NEW_REGS)
#define HEVC_CBREAK_STAUTS_DBE            (0x383a | MASK_S5_NEW_REGS)
#define HEVC_CDB_ADDR_REG_DBE             (0x383b | MASK_S5_NEW_REGS)
#define HEVC_CDB_DATA_REG_DBE             (0x383c | MASK_S5_NEW_REGS)
#define HEVC_CDB_CTRL_DBE                 (0x383d | MASK_S5_NEW_REGS)
#define HEVC_CSFTINT0_DBE                 (0x383e | MASK_S5_NEW_REGS)
#define HEVC_CSFTINT1_DBE                 (0x383f | MASK_S5_NEW_REGS)
#define HEVC_IMEM_DMA_CTRL_DBE            (0x3840 | MASK_S5_NEW_REGS)
#define HEVC_IMEM_DMA_ADR_DBE             (0x3841 | MASK_S5_NEW_REGS)
#define HEVC_IMEM_DMA_COUNT_DBE           (0x3842 | MASK_S5_NEW_REGS)
#define HEVC_WRRSP_IMEM_DBE               (0x3843 | MASK_S5_NEW_REGS)
#define HEVC_LMEM_DMA_CTRL_DBE            (0x3850 | MASK_S5_NEW_REGS)
#define HEVC_LMEM_DMA_ADR_DBE             (0x3851 | MASK_S5_NEW_REGS)
#define HEVC_LMEM_DMA_COUNT_DBE           (0x3852 | MASK_S5_NEW_REGS)
#define HEVC_WRRSP_LMEM_DBE               (0x3853 | MASK_S5_NEW_REGS)
#define HEVC_MAC_CTRL1_DBE                (0x3860 | MASK_S5_NEW_REGS)
#define HEVC_ACC0REG1_DBE                 (0x3861 | MASK_S5_NEW_REGS)
#define HEVC_ACC1REG1_DBE                 (0x3862 | MASK_S5_NEW_REGS)
#define HEVC_MAC_CTRL2_DBE                (0x3870 | MASK_S5_NEW_REGS)
#define HEVC_ACC0REG2_DBE                 (0x3871 | MASK_S5_NEW_REGS)
#define HEVC_ACC1REG2_DBE                 (0x3872 | MASK_S5_NEW_REGS)
#define HEVC_CPU_TRACE_DBE                (0x3880 | MASK_S5_NEW_REGS)

#define HEVCD_IPP_TOP_CNTL_DBE1                    (0x3900 | MASK_S5_NEW_REGS)
#define HEVCD_IPP_TOP_STATUS_DBE1                  (0x3901 | MASK_S5_NEW_REGS)
#define HEVCD_IPP_TOP_FRMCONFIG_DBE1               (0x3902 | MASK_S5_NEW_REGS)
#define HEVCD_IPP_TOP_TILECONFIG1_DBE1             (0x3903 | MASK_S5_NEW_REGS)
#define HEVCD_IPP_TOP_TILECONFIG2_DBE1             (0x3904 | MASK_S5_NEW_REGS)
#define HEVCD_IPP_TOP_TILECONFIG3_DBE1             (0x3905 | MASK_S5_NEW_REGS)
#define HEVCD_IPP_TOP_LCUCONFIG_DBE1               (0x3906 | MASK_S5_NEW_REGS)
#define HEVCD_IPP_TOP_FRMCTL_DBE1                  (0x3907 | MASK_S5_NEW_REGS)
#define HEVCD_IPP_CONFIG_DBE1                      (0x3908 | MASK_S5_NEW_REGS)
#define HEVCD_IPP_LINEBUFF_BASE_DBE1               (0x3909 | MASK_S5_NEW_REGS)
#define HEVCD_IPP_INTR_MASK_DBE1                   (0x390a | MASK_S5_NEW_REGS)
#define HEVCD_IPP_AXIIF_CONFIG_DBE1                (0x390b | MASK_S5_NEW_REGS)
#define HEVCD_IPP_BITDEPTH_CONFIG_DBE1             (0x390c | MASK_S5_NEW_REGS)
#define HEVCD_IPP_RTL_CONFIG_DBE1                  (0x390d | MASK_S5_NEW_REGS)
#define HEVCD_IPP_SHADOWMODE_CNTL_DBE1             (0x390e | MASK_S5_NEW_REGS)
#define HEVCD_IPP_AXIADDR_PREFIX_DBE1              (0x3918 | MASK_S5_NEW_REGS)
#define AV1D_IPP_DIR_CFG_DBE1                      (0x3919 | MASK_S5_NEW_REGS)
#define HEVCD_IPP_DYNCLKGATE_CONFIG_DBE1           (0x3920 | MASK_S5_NEW_REGS)
#define HEVCD_IPP_DYNCLKGATE_STATUS_DBE1           (0x3921 | MASK_S5_NEW_REGS)
#define HEVCD_IPP_DBG_SEL_DBE1                     (0x3930 | MASK_S5_NEW_REGS)
#define HEVCD_IPP_DBG_DATA_DBE1                    (0x3931 | MASK_S5_NEW_REGS)
#define HEVCD_MPP_ANC2AXI_TBL_CONF_ADDR_DBE1       (0x3960 | MASK_S5_NEW_REGS)
#define HEVCD_MPP_ANC2AXI_TBL_DATA_DBE1            (0x3964 | MASK_S5_NEW_REGS)
#define HEVCD_MPP_WEIGHTPRED_CNTL_ADDR_DBE1        (0x397b | MASK_S5_NEW_REGS)
#define HEVCD_MPP_L0_WEIGHT_FLAG_ADDR_DBE1         (0x397c | MASK_S5_NEW_REGS)
#define HEVCD_MPP_L1_WEIGHT_FLAG_ADDR_DBE1         (0x397d | MASK_S5_NEW_REGS)
#define HEVCD_MPP_YLOG2WGHTDENOM_ADDR_DBE1         (0x397e | MASK_S5_NEW_REGS)
#define HEVCD_MPP_DELTACLOG2WGHTDENOM_ADDR_DBE1    (0x397f | MASK_S5_NEW_REGS)
#define HEVCD_MPP_WEIGHT_ADDR_DBE1                 (0x3980 | MASK_S5_NEW_REGS)
#define HEVCD_MPP_WEIGHT_DATA_DBE1                 (0x3981 | MASK_S5_NEW_REGS)

/* s6 */
#define VVC_MPP_REF0_POC_CFG_DBE1                  0x39b0
#define VVC_MPP_REF1_POC_CFG_DBE1                  0x39b1
#define VVC_MPP_REF_IS_LONGTERM_DBE1               0x39b2
#define VVC_MPP_CHROMA_COLLOCATED_CFG_DBE1         0x39b3
#define VVC_MPP_REF_WRAPAROUND_CFG_DBE1            0x39b4
#define VVC_MPP_SUBPIC_START_DBE1                  0x39b5
#define VVC_MPP_SUBPIC_SIZE_DBE1                   0x39b6
#define VVC_MPP_SCALING_WIN_OFFSET_DBE1            0x39b7
#define VVC_MPP_CURR_PROF_ENABLE_DBE1              0x39b8
#define VVC_MPP_CANVAS_ID_L0_DBE1                  0x39b9
#define VVC_MPP_CANVAS_ID_L1_DBE1                  0x39ba
#define VVC_MPP_MV_WRPTR_DBE1                      0x39bb
#define VVC_MPP_SLICE_INFO_DBE1                    0x39bc
#define VVC_MPP_AXI_CTL_DBE1                       0x39bd
#define VVC_MPP_LCU_INFO_DBE1                      0x39be
#define VVC_MPP_RPR_REFINFO_DBE1                   0x39bf

#define HEVCD_MPP_ANC_CANVAS_ACCCONFIG_ADDR_DBE1   (0x39c0 | MASK_S5_NEW_REGS)
#define HEVCD_MPP_ANC_CANVAS_DATA_ADDR_DBE1        (0x39c1 | MASK_S5_NEW_REGS)
#define HEVCD_MPP_DECOMP_CTL1_DBE1                 (0x39c2 | MASK_S5_NEW_REGS)
#define HEVCD_MPP_DECOMP_CTL2_DBE1                 (0x39c3 | MASK_S5_NEW_REGS)
#define HEVCD_MPP_DECOMP_CTL3_DBE1                 (0x39c4 | MASK_S5_NEW_REGS)
#define HEVCD_MPP_DECOMP_PERFMON_CTL_DBE1          (0x39c5 | MASK_S5_NEW_REGS)
#define HEVCD_MPP_DECOMP_PERFMON_DATA_DBE1         (0x39c6 | MASK_S5_NEW_REGS)
#define HEVCD_MPP_DECOMP_AXIURG_CTL_DBE1           (0x39c7 | MASK_S5_NEW_REGS)
#define HEVCD_MPP_VDEC_MCR_CTL_DBE1                (0x39c8 | MASK_S5_NEW_REGS)
#define HEVCD_MCRCC_CTL1_DBE1                      (0x39f0 | MASK_S5_NEW_REGS)
#define HEVCD_MCRCC_CTL2_DBE1                      (0x39f1 | MASK_S5_NEW_REGS)
#define HEVCD_MCRCC_CTL3_DBE1                      (0x39f2 | MASK_S5_NEW_REGS)
#define HEVCD_MCRCC_PERFMON_CTL_DBE1               (0x39f3 | MASK_S5_NEW_REGS)
#define HEVCD_MCRCC_PERFMON_DATA_DBE1              (0x39f4 | MASK_S5_NEW_REGS)
#define HEVCD_MCRCC_STALL_ADJUST_DBE1              (0x39f5 | MASK_S5_NEW_REGS)
#define VP9D_MPP_INTERPOL_CFG0_DBE1                (0x3940 | MASK_S5_NEW_REGS)
#define VP9D_MPP_REF_SCALE_ENBL_DBE1               (0x3941 | MASK_S5_NEW_REGS)
#define VP9D_MPP_REFINFO_TBL_ACCCONFIG_DBE1        (0x3942 | MASK_S5_NEW_REGS)
#define VP9D_MPP_REFINFO_DATA_DBE1                 (0x3943 | MASK_S5_NEW_REGS)
#define AV1D_MPP_REF2WMMAT_TBL_CONF_ADDR_DBE1      (0x3991 | MASK_S5_NEW_REGS)
#define AV1D_MPP_REF2WMMAT_TBL_DATA_DBE1           (0x3992 | MASK_S5_NEW_REGS)
#define AV1D_MPP_ORDERHINT_CFG_DBE1                (0x3993 | MASK_S5_NEW_REGS)
#define AV1D_MPP_MISC_CFG_DBE1                     (0x3994 | MASK_S5_NEW_REGS)
#define HEVCD_IPP_MULTICORE_CFG_DBE1               (0x39a0 | MASK_S5_NEW_REGS)
#define HEVCD_IPP_MULTICORE_LINE_CTL_DBE1          (0x39a1 | MASK_S5_NEW_REGS)
#define HEVCD_IPP_LINEBUFF_BASE2_DBE1              (0x39a2 | MASK_S5_NEW_REGS)
#define HEVCD_IPP_DYN_CACHE_DBE1                   (0x39a3 | MASK_S5_NEW_REGS)
#define HEVCD_IPP_CTRL0_DBE1                       (0x39a4 | MASK_S5_NEW_REGS)
#define HEVCD_IPP_CTRL1_DBE1                       (0x39a5 | MASK_S5_NEW_REGS)
#define HEVCD_IPP_CTRL2_DBE1                       (0x39a6 | MASK_S5_NEW_REGS)
#define HEVCD_IPP_CTRL3_DBE1                       (0x39a7 | MASK_S5_NEW_REGS)
#define HEVC_DBLK_CFG0_DBE1                        (0x3a00 | MASK_S5_NEW_REGS)
#define HEVC_DBLK_CFG1_DBE1                        (0x3a01 | MASK_S5_NEW_REGS)
#define HEVC_DBLK_CFG2_DBE1                        (0x3a02 | MASK_S5_NEW_REGS)
#define HEVC_DBLK_CFG3_DBE1                        (0x3a03 | MASK_S5_NEW_REGS)
#define HEVC_DBLK_CFG4_DBE1                        (0x3a04 | MASK_S5_NEW_REGS)
#define HEVC_DBLK_CFG5_DBE1                        (0x3a05 | MASK_S5_NEW_REGS)
#define HEVC_DBLK_CFG6_DBE1                        (0x3a06 | MASK_S5_NEW_REGS)
#define HEVC_DBLK_CFG7_DBE1                        (0x3a07 | MASK_S5_NEW_REGS)
#define HEVC_DBLK_CFG8_DBE1                        (0x3a08 | MASK_S5_NEW_REGS)
#define HEVC_DBLK_CFG9_DBE1                        (0x3a09 | MASK_S5_NEW_REGS)
#define HEVC_DBLK_CFGA_DBE1                        (0x3a0a | MASK_S5_NEW_REGS)
#define HEVC_DBLK_CFGB_DBE1                        (0x3a0b | MASK_S5_NEW_REGS)
#define HEVC_DBLK_CFGC_DBE1                        (0x3a0c | MASK_S5_NEW_REGS)
#define HEVC_DBLK_CFGD_DBE1                        (0x3a0d | MASK_S5_NEW_REGS)
#define HEVC_DBLK_CFGE_DBE1                        (0x3a0e | MASK_S5_NEW_REGS)
#define HEVC_DBLK_STS0_DBE1                        (0x3a0f | MASK_S5_NEW_REGS)
#define HEVC_DBLK_STS1_DBE1                        (0x3a10 | MASK_S5_NEW_REGS)
#define HEVC_DBLK_CFG11_DBE1                       (0x3a11 | MASK_S5_NEW_REGS)
#define HEVC_DBLK_CFG12_DBE1                       (0x3a12 | MASK_S5_NEW_REGS)
#define HEVC_DBLK_CFG13_DBE1                       (0x3a13 | MASK_S5_NEW_REGS)
#define HEVC_DBLK_CFG14_DBE1                       (0x3a14 | MASK_S5_NEW_REGS)
#define HEVC_DBLK_CDEF0_DBE1                       (0x3a15 | MASK_S5_NEW_REGS)
#define HEVC_DBLK_CDEF1_DBE1                       (0x3a16 | MASK_S5_NEW_REGS)
#define HEVC_DBLK_CDEF2_DBE1                       (0x3a17 | MASK_S5_NEW_REGS)
#define HEVC_DBLK_CDEF3_DBE1                       (0x3a18 | MASK_S5_NEW_REGS)
#define HEVC_DBLK_CDEF4_DBE1                       (0x3a19 | MASK_S5_NEW_REGS)
#define HEVC_DBLK_CDEF5_DBE1                       (0x3a1a | MASK_S5_NEW_REGS)
#define HEVC_DBLK_UPS0_DBE1                        (0x3a1b | MASK_S5_NEW_REGS)
#define HEVC_DBLK_UPS1_DBE1                        (0x3a1c | MASK_S5_NEW_REGS)
#define HEVC_DBLK_UPS2_DBE1                        (0x3a1d | MASK_S5_NEW_REGS)
#define HEVC_DBLK_UPS3_DBE1                        (0x3a1e | MASK_S5_NEW_REGS)
#define HEVC_DBLK_UPS4_DBE1                        (0x3a1f | MASK_S5_NEW_REGS)
#define HEVC_DBLK_UPS5_DBE1                        (0x3a20 | MASK_S5_NEW_REGS)
#define HEVC_DBLK_LRF0_DBE1                        (0x3a21 | MASK_S5_NEW_REGS)
#define HEVC_DBLK_LRF1_DBE1                        (0x3a22 | MASK_S5_NEW_REGS)
#define HEVC_DBLK_DBLK0_DBE1                       (0x3a23 | MASK_S5_NEW_REGS)
#define HEVC_DBLK_DBLK1_DBE1                       (0x3a24 | MASK_S5_NEW_REGS)
#define HEVC_DBLK_DBLK2_DBE1                       (0x3a25 | MASK_S5_NEW_REGS)
#define HEVC_DBLK_PREFIX_DBE1                      (0x3a26 | MASK_S5_NEW_REGS)
#define HEVC_DBLK_BUSYSEL_DBE1                     (0x3a27 | MASK_S5_NEW_REGS)
#define HEVC_DBLK_SHADOWMODE_CNTL_DBE1             (0x3a28 | MASK_S5_NEW_REGS)
#define HEVC_DBLK_MCP_DBE1                         (0x3a29 | MASK_S5_NEW_REGS)
#define HEVC_DBLK_SLICNT_DBE1                      (0x3a2a | MASK_S5_NEW_REGS)
#define HEVC_DBLK_INTRPT_DBE1                      (0x3a2b | MASK_S5_NEW_REGS)

#define HEVC_DBLK_LMCS_DELTA_CW_INDEX_DBE1         0x3a2c
#define HEVC_DBLK_LMCS_DELTA_CW_DATA_DBE1          0x3a2d
#define HEVC_DBLK_LMCS_DELTA_CTRL_DBE1             0x3a2e
#define HEVC_DBLK_SAO0_DBE1                        0x3a40
#define HEVC_DBLK_SAO1_DBE1                        0x3a41
#define HEVC_DBLK_SAO2_DBE1                        0x3a42
#define HEVC_DBLK_SAO3_DBE1                        0x3a43
#define HEVC_DBLK_ALF0_DBE1                        0x3a44
#define HEVC_DBLK_ALF1_DBE1                        0x3a45
#define HEVC_DBLK_ALF2_DBE1                        0x3a46
#define HEVC_DBLK_ALF3_DBE1                        0x3a47
#define HEVC_DBLK_VBVER_DBE1                       0x3a48
#define HEVC_DBLK_VBVER1_DBE1                      0x3a49
#define HEVC_DBLK_VBHOR_DBE1                       0x3a4a
#define HEVC_DBLK_VBHOR1_DBE1                      0x3a4b
#define HEVC_DBLK_SUBPIC_DBE1                      0x3a4c
#define HEVC_DBLK_EOT_DBE1                         0x3a4d

#define HEVC_SAO_VERSION_DBE1                      (0x3b00 | MASK_S5_NEW_REGS)
#define HEVC_SAO_CTRL0_DBE1                        (0x3b01 | MASK_S5_NEW_REGS)
#define HEVC_SAO_CTRL1_DBE1                        (0x3b02 | MASK_S5_NEW_REGS)
#define HEVC_SAO_INT_EN_DBE1                       (0x3b03 | MASK_S5_NEW_REGS)
#define HEVC_SAO_INT_STATUS_DBE1                   (0x3b04 | MASK_S5_NEW_REGS)
#define HEVC_SAO_PIC_SIZE_DBE1                     (0x3b05 | MASK_S5_NEW_REGS)
#define HEVC_SAO_PIC_SIZE_LCU_DBE1                 (0x3b06 | MASK_S5_NEW_REGS)
#define HEVC_SAO_TILE_START_DBE1                   (0x3b07 | MASK_S5_NEW_REGS)
#define HEVC_SAO_TILE_SIZE_LCU_DBE1                (0x3b08 | MASK_S5_NEW_REGS)
#define HEVC_SAO_AXI_WCTRL_DBE1                    (0x3b09 | MASK_S5_NEW_REGS)
#define HEVC_SAO_AXI_RCTRL_DBE1                    (0x3b0a | MASK_S5_NEW_REGS)
#define HEVC_SAO_Y_START_ADDR_DBE1                 (0x3b0b | MASK_S5_NEW_REGS)
#define HEVC_SAO_Y_LENGTH_DBE1                     (0x3b0c | MASK_S5_NEW_REGS)
#define HEVC_SAO_C_START_ADDR_DBE1                 (0x3b0d | MASK_S5_NEW_REGS)
#define HEVC_SAO_C_LENGTH_DBE1                     (0x3b0e | MASK_S5_NEW_REGS)
#define HEVC_SAO_Y_WPTR_DBE1                       (0x3b0f | MASK_S5_NEW_REGS)
#define HEVC_SAO_C_WPTR_DBE1                       (0x3b10 | MASK_S5_NEW_REGS)
#define HEVC_SAO_ABV_START_ADDR_DBE1               (0x3b11 | MASK_S5_NEW_REGS)
#define HEVC_SAO_VB_WR_START_ADDR_DBE1             (0x3b12 | MASK_S5_NEW_REGS)
#define HEVC_SAO_VB_RD_START_ADDR_DBE1             (0x3b13 | MASK_S5_NEW_REGS)
#define HEVC_SAO_ABV_WPTR_DBE1                     (0x3b14 | MASK_S5_NEW_REGS)
#define HEVC_SAO_ABV_RPTR_DBE1                     (0x3b15 | MASK_S5_NEW_REGS)
#define HEVC_SAO_VB_WPTR_DBE1                      (0x3b16 | MASK_S5_NEW_REGS)
#define HEVC_SAO_VB_RPTR_DBE1                      (0x3b17 | MASK_S5_NEW_REGS)
#define HEVC_SAO_DBG_MODE0_DBE1                    (0x3b1e | MASK_S5_NEW_REGS)
#define HEVC_SAO_DBG_MODE1_DBE1                    (0x3b1f | MASK_S5_NEW_REGS)
#define HEVC_SAO_CTRL2_DBE1                        (0x3b20 | MASK_S5_NEW_REGS)
#define HEVC_SAO_CTRL3_DBE1                        (0x3b21 | MASK_S5_NEW_REGS)
#define HEVC_SAO_CTRL4_DBE1                        (0x3b22 | MASK_S5_NEW_REGS)
#define HEVC_SAO_CTRL5_DBE1                        (0x3b23 | MASK_S5_NEW_REGS)
#define HEVC_SAO_CTRL6_DBE1                        (0x3b24 | MASK_S5_NEW_REGS)
#define HEVC_SAO_CTRL7_DBE1                        (0x3b25 | MASK_S5_NEW_REGS)
#define HEVC_CM_BODY_START_ADDR_DBE1               (0x3b26 | MASK_S5_NEW_REGS)
#define HEVC_CM_BODY_LENGTH_DBE1                   (0x3b27 | MASK_S5_NEW_REGS)
#define HEVC_CM_HEADER_START_ADDR_DBE1             (0x3b28 | MASK_S5_NEW_REGS)
#define HEVC_CM_HEADER_LENGTH_DBE1                 (0x3b29 | MASK_S5_NEW_REGS)
#define HEVC_CM_COLOR_DBE1                         (0x3b2a | MASK_S5_NEW_REGS)
#define HEVC_CM_HEADER_OFFSET_DBE1                 (0x3b2b | MASK_S5_NEW_REGS)
#define HEVC_SAO_CTRL8_DBE1                        (0x3b2c | MASK_S5_NEW_REGS)
#define HEVC_SAO_CTRL9_DBE1                        (0x3b2d | MASK_S5_NEW_REGS)
#define HEVC_SAO_CTRL10_DBE1                       (0x3b2e | MASK_S5_NEW_REGS)
#define HEVC_SAO_CTRL11_DBE1                       (0x3b2f | MASK_S5_NEW_REGS)
#define HEVC_SAO_DBG_DATA_0_DBE1                   (0x3b30 | MASK_S5_NEW_REGS)
#define HEVC_SAO_DBG_DATA_1_DBE1                   (0x3b31 | MASK_S5_NEW_REGS)
#define HEVC_SAO_DBG_DATA_2_DBE1                   (0x3b32 | MASK_S5_NEW_REGS)
#define HEVC_SAO_DBG_DATA_3_DBE1                   (0x3b33 | MASK_S5_NEW_REGS)
#define HEVC_SAO_DBG_DATA_4_DBE1                   (0x3b34 | MASK_S5_NEW_REGS)
#define HEVC_SAO_DBG_DATA_5_DBE1                   (0x3b35 | MASK_S5_NEW_REGS)
#define HEVC_SAO_DBG_DATA_6_DBE1                   (0x3b36 | MASK_S5_NEW_REGS)
#define HEVC_SAO_DBG_DATA_7_DBE1                   (0x3b37 | MASK_S5_NEW_REGS)
#define HEVC_SAO_MMU_WR_DBE1                       (0x3b38 | MASK_S5_NEW_REGS)
#define HEVC_SAO_MMU_STATUS_DBE1                   (0x3b39 | MASK_S5_NEW_REGS)
#define HEVC_SAO_MMU_VH0_ADDR_DBE1                 (0x3b3a | MASK_S5_NEW_REGS)
#define HEVC_SAO_MMU_VH1_ADDR_DBE1                 (0x3b3b | MASK_S5_NEW_REGS)
#define HEVC_SAO_MMU_WPTR_DBE1                     (0x3b3c | MASK_S5_NEW_REGS)
#define HEVC_SAO_MMU_RPTR_DBE1                     (0x3b3d | MASK_S5_NEW_REGS)
#define HEVC_SAO_MMU_DMA_CTRL_DBE1                 (0x3b3e | MASK_S5_NEW_REGS)
#define HEVC_SAO_MMU_DMA_STATUS_DBE1               (0x3b3f | MASK_S5_NEW_REGS)
#define HEVC_CM_CORE_STATUS_DBE1                   (0x3b40 | MASK_S5_NEW_REGS)
#define HEVC_SAO_MMU_RESET_CTRL_DBE1               (0x3b41 | MASK_S5_NEW_REGS)
#define HEVC_CM_LOSSY_QUANT_CTRL_DBE1              (0x3b42 | MASK_S5_NEW_REGS)
#define HEVC_CM_LOSSY_RQUANT_YCLUT_ACCCONFIG_DBE1  (0x3b43 | MASK_S5_NEW_REGS)
#define HEVC_CM_LOSSY_RQUANT_YCLUT_DATA_DBE1       (0x3b44 | MASK_S5_NEW_REGS)
#define HEVC_CM_LOSSY_IQUANT_YCLUT_ACCCONFIG_DBE1  (0x3b45 | MASK_S5_NEW_REGS)
#define HEVC_CM_LOSSY_IQUANT_YCLUT_DATA_DBE1       (0x3b46 | MASK_S5_NEW_REGS)
#define HEVC_CM_AV1_TILE_LOC_X_DBE1                (0x3b47 | MASK_S5_NEW_REGS)
#define HEVC_CM_AV1_TILE_LOC_Y_DBE1                (0x3b48 | MASK_S5_NEW_REGS)
#define HEVC_CM_CORE_CTRL_DBE1                     (0x3b49 | MASK_S5_NEW_REGS)
#define HEVC_CM_HEADER_START_ADDR2_DBE1            (0x3b4a | MASK_S5_NEW_REGS)
#define HEVC_SAO_MMU_WR2_DBE1                      (0x3b4b | MASK_S5_NEW_REGS)
#define HEVC_SAO_MMU_DMA_CTRL2_DBE1                (0x3b4c | MASK_S5_NEW_REGS)
#define HEVC_SAO_MMU_VH0_ADDR2_DBE1                (0x3b4d | MASK_S5_NEW_REGS)
#define HEVC_SAO_MMU_VH1_ADDR2_DBE1                (0x3b4e | MASK_S5_NEW_REGS)
#define HEVC_CM_CORE_STATUS2_DBE1                  (0x3b4f | MASK_S5_NEW_REGS)
#define HEVC_SAO_MMU_STATUS2_DBE1                  (0x3b50 | MASK_S5_NEW_REGS)
#define HEVC_CM_LOSSY_QUANT_CTRL2_DBE1             (0x3b52 | MASK_S5_NEW_REGS)
#define HEVC_CM_LOSSY_RQUANT_YCLUT_ACCCONFIG2_DBE1 (0x3b53 | MASK_S5_NEW_REGS)
#define HEVC_CM_LOSSY_RQUANT_YCLUT_DATA2_DBE1      (0x3b54 | MASK_S5_NEW_REGS)
#define HEVC_CM_LOSSY_IQUANT_YCLUT_ACCCONFIG2_DBE1 (0x3b55 | MASK_S5_NEW_REGS)
#define HEVC_CM_LOSSY_IQUANT_YCLUT_DATA2_DBE1      (0x3b56 | MASK_S5_NEW_REGS)
#define HEVC_CM_AV1_TILE_LOC_X2_DBE1               (0x3b57 | MASK_S5_NEW_REGS)
#define HEVC_CM_AV1_TILE_LOC_Y2_DBE1               (0x3b58 | MASK_S5_NEW_REGS)
#define HEVC_CM_CORE_CTRL2_DBE1                    (0x3b59 | MASK_S5_NEW_REGS)
#define HEVC_CM_BODY_START_ADDR2_DBE1              (0x3b5a | MASK_S5_NEW_REGS)
#define HEVC_FORCE_YUV_CTRL_DBE1                   (0x3b5b | MASK_S5_NEW_REGS)
#define HEVC_FORCE_YUV_0_DBE1                      (0x3b5c | MASK_S5_NEW_REGS)
#define HEVC_FORCE_YUV_1_DBE1                      (0x3b5d | MASK_S5_NEW_REGS)
#define HEVC_DW_VH0_ADDDR_DBE1                     (0x3b5e | MASK_S5_NEW_REGS)
#define HEVC_DW_VH1_ADDDR_DBE1                     (0x3b5f | MASK_S5_NEW_REGS)
#define HEVC_FGS_IDX_DBE1                          (0x3b60 | MASK_S5_NEW_REGS)
#define HEVC_FGS_DATA_DBE1                         (0x3b61 | MASK_S5_NEW_REGS)
#define HEVC_FGS_CTRL_DBE1                         (0x3b62 | MASK_S5_NEW_REGS)
#define HEVC_CM_BODY_LENGTH2_DBE1                  (0x3b63 | MASK_S5_NEW_REGS)
#define HEVC_CM_HEADER_OFFSET2_DBE1                (0x3b64 | MASK_S5_NEW_REGS)
#define HEVC_CM_HEADER_LENGTH2_DBE1                (0x3b65 | MASK_S5_NEW_REGS)
#define HEVC_FGS_TABLE_START_DBE1                  (0x3b66 | MASK_S5_NEW_REGS)
#define HEVC_FGS_TABLE_LENGTH_DBE1                 (0x3b67 | MASK_S5_NEW_REGS)
#define HEVC_OW_FRAME_CNT_DBE1                     (0x3b68 | MASK_S5_NEW_REGS)
#define HEVC_SAO_CTRL12_DBE1                       (0x3b69 | MASK_S5_NEW_REGS)
#define HEVC_SAO_CTRL13_DBE1                       (0x3b6a | MASK_S5_NEW_REGS)
#define HEVC_SAO_CTRL14_DBE1                       (0x3b6b | MASK_S5_NEW_REGS)
#define HEVC_SAO_CTRL15_DBE1                       (0x3b6c | MASK_S5_NEW_REGS)
#define HEVC_SAO_CTRL16_DBE1                       (0x3b6d | MASK_S5_NEW_REGS)
#define HEVC_SAO_CTRL17_DBE1                       (0x3b6e | MASK_S5_NEW_REGS)
#define HEVC_SAO_CTRL18_DBE1                       (0x3b6f | MASK_S5_NEW_REGS)
#define HEVC_SAO_CTRL19_DBE1                       (0x3b70 | MASK_S5_NEW_REGS)
#define HEVC_SAO_CTRL20_DBE1                       (0x3b71 | MASK_S5_NEW_REGS)
#define HEVC_SAO_CTRL21_DBE1                       (0x3b72 | MASK_S5_NEW_REGS)
#define HEVC_SAO_CTRL22_DBE1                       (0x3b73 | MASK_S5_NEW_REGS)
#define HEVC_SAO_CTRL23_DBE1                       (0x3b74 | MASK_S5_NEW_REGS)
#define HEVC_SAO_CTRL24_DBE1                       (0x3b75 | MASK_S5_NEW_REGS)
#define HEVC_SAO_CTRL25_DBE1                       (0x3b76 | MASK_S5_NEW_REGS)
#define HEVC_SAO_CTRL26_DBE1                       (0x3b77 | MASK_S5_NEW_REGS)
#define HEVC_SAO_CTRL27_DBE1                       (0x3b78 | MASK_S5_NEW_REGS)
#define HEVC_SAO_CTRL28_DBE1                       (0x3b79 | MASK_S5_NEW_REGS)
#define HEVC_SAO_CTRL29_DBE1                       (0x3b7a | MASK_S5_NEW_REGS)
#define HEVC_SAO_CTRL30_DBE1                       (0x3b7b | MASK_S5_NEW_REGS)
#define HEVC_SAO_CTRL31_DBE1                       (0x3b7c | MASK_S5_NEW_REGS)
#define HEVC_SAO_CTRL32_DBE1                       (0x3b7d | MASK_S5_NEW_REGS)
#define HEVC_OW_AXIADDR_PREFIX_DBE1                (0x3b7e | MASK_S5_NEW_REGS)
#define HEVC_OW_AXIADDR_PREFIX2_DBE1               (0x3b7f | MASK_S5_NEW_REGS)
#define HEVC_SAO_STATUS0_DBE1                      (0x3b80 | MASK_S5_NEW_REGS)
#define HEVC_SAO_STATUS1_DBE1                      (0x3b81 | MASK_S5_NEW_REGS)
#define HEVC_SAO_STATUS2_DBE1                      (0x3b82 | MASK_S5_NEW_REGS)
#define HEVC_SAO_STATUS3_DBE1                      (0x3b83 | MASK_S5_NEW_REGS)
#define HEVC_SAO_STATUS4_DBE1                      (0x3b84 | MASK_S5_NEW_REGS)
#define HEVC_SAO_STATUS5_DBE1                      (0x3b85 | MASK_S5_NEW_REGS)
#define HEVC_SAO_STATUS6_DBE1                      (0x3b86 | MASK_S5_NEW_REGS)
#define HEVC_SAO_STATUS7_DBE1                      (0x3b87 | MASK_S5_NEW_REGS)
#define COPY_REG_R0_DBE1                           (0x3b88 | MASK_S5_NEW_REGS)
#define COPY_REG_R1_DBE1                           (0x3b89 | MASK_S5_NEW_REGS)
#define COPY_SEL_DBE1                              (0x3b8a | MASK_S5_NEW_REGS)
#define COPY_REG_R3_DBE1                           (0x3b8b | MASK_S5_NEW_REGS)
#define COPY_REG_R4_DBE1                           (0x3b8c | MASK_S5_NEW_REGS)
#define COPY_REG_R5_DBE1                           (0x3b8d | MASK_S5_NEW_REGS)
#define HEVC_SAO_SHADOWMODE_CNTL_DBE1              (0x3b8e | MASK_S5_NEW_REGS)
#define HEVC_SAO_CRC_DBE1                          (0x3b90 | MASK_S5_NEW_REGS)
#define HEVC_SAO_CRC_Y_DBE1                        (0x3b91 | MASK_S5_NEW_REGS)
#define HEVC_SAO_CRC_C_DBE1                        (0x3b92 | MASK_S5_NEW_REGS)

#define HEVC_SAO_CRC_1_DBE1                        0x3b93
#define HEVC_SAO_CRC_2_DBE1                        0x3b94
#define HEVC_SAO_CRC_3_DBE1                        0x3b95
#define HEVC_SAO_CRC_4_DBE1                        0x3b96
#define HEVC_SAO_CRC_5_DBE1                        0x3b97
#define HEVC_SAO_Y_START_ADDR3_DBE1                0x3b98
#define HEVC_SAO_Y_LENGTH3_DBE1                    0x3b99
#define HEVC_SAO_C_START_ADDR3_DBE1                0x3b9a
#define HEVC_SAO_C_LENGTH3_DBE1                    0x3b9b
#define HEVC_FORCE_YUV_2_DBE1                      0x3b9c
#define HEVC_SAO_AXI_CTRL_DBE1                     0x3b9d

#define HEVC_SAO_Y2_START_ADDR_DBE1                0x3ba0
#define HEVC_SAO_Y2_LENGTH_DBE1                    0x3ba1
#define HEVC_SAO_C2_START_ADDR_DBE1                0x3ba2
#define HEVC_SAO_C2_LENGTH_DBE1                    0x3ba3
#define HEVC_SAO_TILE_IDX_DBE1                     0x3ba4

#define HEVC_IQIT_CLK_RST_CTRL_DBE1                (0x3c00 | MASK_S5_NEW_REGS)
#define HEVC_IQIT_DEQUANT_CTRL_DBE1                (0x3c01 | MASK_S5_NEW_REGS)
#define HEVC_IQIT_SCALELUT_WR_ADDR_DBE1            (0x3c02 | MASK_S5_NEW_REGS)
#define HEVC_IQIT_SCALELUT_RD_ADDR_DBE1            (0x3c03 | MASK_S5_NEW_REGS)
#define HEVC_IQIT_SCALELUT_DATA_DBE1               (0x3c04 | MASK_S5_NEW_REGS)
#define HEVC_IQIT_SCALELUT_IDX_4_DBE1              (0x3c05 | MASK_S5_NEW_REGS)
#define HEVC_IQIT_SCALELUT_IDX_8_DBE1              (0x3c06 | MASK_S5_NEW_REGS)
#define HEVC_IQIT_SCALELUT_IDX_16_32_DBE1          (0x3c07 | MASK_S5_NEW_REGS)
#define HEVC_IQIT_STAT_GEN0_DBE1                   (0x3c08 | MASK_S5_NEW_REGS)
#define HEVC_QP_WRITE_DBE1                         (0x3c09 | MASK_S5_NEW_REGS)
#define HEVC_IQIT_STAT_GEN1_DBE1                   (0x3c0a | MASK_S5_NEW_REGS)
#define HEVC_IQIT_BITDEPTH_DBE1                    (0x3c0b | MASK_S5_NEW_REGS)
#define HEVC_IQIT_STAT_GEN2_DBE1                   (0x3c0c | MASK_S5_NEW_REGS)
#define HEVC_IQIT_AVS2_WQP_0123_DBE1               (0x3c0d | MASK_S5_NEW_REGS)
#define HEVC_IQIT_AVS2_WQP_45_DBE1                 (0x3c0e | MASK_S5_NEW_REGS)
#define HEVC_IQIT_AVS2_QP_DELTA_DBE1               (0x3c0f | MASK_S5_NEW_REGS)
#define HEVC_PIC_QUALITY_CTRL_DBE1                 (0x3c10 | MASK_S5_NEW_REGS)
#define HEVC_PIC_QUALITY_DATA_DBE1                 (0x3c11 | MASK_S5_NEW_REGS)
#define HEVC_PATH_MONITOR_CTRL_DBE1                (0x3c12 | MASK_S5_NEW_REGS)
#define HEVC_PATH_MONITOR_DATA_DBE1                (0x3c13 | MASK_S5_NEW_REGS)
#define HEVC_IQIT_STAT_GEN3_DBE1                   (0x3c20 | MASK_S5_NEW_REGS)
#define HEVC_IQIT_STAT_GEN4_DBE1                   (0x3c21 | MASK_S5_NEW_REGS)
#define HEVC_IQIT_STAT_GEN5_DBE1                   (0x3c22 | MASK_S5_NEW_REGS)

#endif // DOS_REGS_FB_HEADER_

