# Overlays for the Odroid platform

dtbo-y += \
	spidev1-overlay.dtbo \
	i2c1-overlay.dtbo \
	i2c5-overlay.dtbo \
	hktft32-overlay.dtbo \
	hktft35-overlay.dtbo \
	hktft-cs-ogst-overlay.dtbo

targets += $(dtbo-y)
always	:= $(dtbo-y)
