# Overlays for the Odroid platform

dtbo-y += \
	spi0.dtbo		\
	i2c0.dtbo		\
	i2c1.dtbo		\
	uart0.dtbo		\
	hktft32.dtbo		\
	hktft35.dtbo		\
	ads7846.dtbo		\
	sx865x-i2c1.dtbo	\
	hktft-cs-ogst.dtbo

targets += $(dtbo-y)
always	:= $(dtbo-y)
