# Overlays for the Odroid platform

dtbo-$(CONFIG_ARCH_MESON64_ODROIDC4) += spi0.dtbo	\
					i2c2.dtbo	\
					i2c3.dtbo	\
					uarta.dtbo	\
					uartb.dtbo	\
					uartc.dtbo	\
					hktft32.dtbo	\
					hktft35.dtbo	\
					pcf8563.dtbo	\
					pcm5242.dtbo

targets	+= $(dtbo-y)
always	:= $(dtbo-y)
